### ISSUE TITLE
The option `--use-webroot-dir` is ignored when creating a Joomla site (site:create)

### ISSUE THREAD

**Issue by sellerie98** [joomlatools/joomlatools-console#121]
### Describe your environment

  * OS: Debian 10
  * Joomla version: 3.9.18
  * Joomlatools Console version:  master (4a08c2c1a9dffd9afe99ead03318db7019f799e5)
  * Are you working on the Joomlatools Vagrant box: no

#### Steps to reproduce:

  1. Build console.phar with `https://github.com/clue/phar-composer` using `php ~/phar-composer-latest.phar build /home/<user>/git/joomlatools-console`
  2. Add the `joomla3.users.sql` file manually using:
```
<?php
try {
    $a = new Phar('console.phar');
    $a->addFile('joomla3.users.sql', 'bin/.files/joomla3.users.sql');

} catch (Exception $e) {
    var_dump($e);
}
?>
```
3. Run `console.phar`:
`~/console.phar site:create --www ${WEB___DIR} --use-webroot-dir --skip-create-statement --mysql-host ${DB_main_HOST} --mysql-login ${DB_main_LOGIN}:${DB_main_PASSWORD} --mysql-database ${DB_main_NAME} --release=${joomla_version} ${SETTINGS_title}`

#### Observed Results:
* The command "succeeds", but
* The Joomla files are downloaded in `${WEB___DIR}/${SETTINGS_title}` where `${WEB___DIR}` corresponds to `www` and `${SETTINGS_title}` corresponds to `site`.

#### Expected Results:
* The Joomla files are downloaded in `${WEB___DIR}/` where `${WEB___DIR}` corresponds to `www`.

**Comment by stevenrombauts** [comment]
@sellerie98 Thanks for reporting this issue, we've pushed a fix and tagged a new v1.5.7 release for it.

**Comment by SteenSchutt** [comment]
@stevenrombauts I noticed while testing this change in my environment, that you forgot to update the version in the code :)
https://github.com/joomlatools/joomlatools-console/blob/master/src/Joomlatools/Console/Application.php#L14

**Comment by stevenrombauts** [comment]
@SteenSchutt 🤦‍♂️ Not the first time I forgot about that! Thanks for letting me know, I've updated it and re-tagged. Could take a little while before Packagist picks it up too.
